project:
  type: website
  output-dir: docs

website:
  title: "Queer Ecologies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - syllabus.qmd
      - resources.qmd
      - text: "Course"
        menu: 
          - course/week1.qmd
          - course/week2.qmd
format:
  html:
    theme: 
      - custom.scss
    mainfont: Quicksand
    css: styles.css
    toc: true

editor: visual

