project:
  type: website
  output-dir: docs

website:
  title: "Queer Ecologies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - syllabus.qmd
      - resources.qmd
      - text: "Course"
        menu: 
          - course/schedule.qmd
          - course/week1.qmd
          - course/week2.qmd
          - course/week3.qmd
          - course/week4.qmd
          - course/week5.qmd
          - course/week6.qmd
          - course/week7.qmd
          - course/week8.qmd
          - course/week9.qmd
          - course/week10.qmd
      - text: "2023 offering"
        menu:
          - 2023/week1.qmd
          - 2023/week2.qmd
          - 2023/week3.qmd
          - 2023/week4.qmd
          - 2023/week5.qmd
          - 2023/week6.qmd
          - 2023/week7.qmd
          - 2023/week8.qmd
          - 2023/week9.qmd
          - 2023/week10.qmd
          - assessment.qmd



format:
  html:
    theme: 
      - custom.scss
    mainfont: Quicksand
    css: styles.css
    toc: true

editor: visual

