project:
  type: website
  output-dir: docs

website:
  title: "Queer Ecologies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - syllabus.qmd
#      - resources.qmd
      - assessment.qmd
      - text: "2025"
        menu:
          - 2025/week1.qmd
          - 2025/week2.qmd
          - 2025/week3.qmd
          - 2025/week4.qmd
          - 2025/week5.qmd
          - 2025/week6.qmd
          - 2025/week7.qmd
          - 2025/week8.qmd
          - 2025/week9.qmd
          - 2025/week10.qmd
      - text: "2024"
        menu: 
          - 2024/schedule.qmd
          - 2024/week1.qmd
          - 2024/week2.qmd
          - 2024/week3.qmd
          - 2024/week4.qmd
          - 2024/week5.qmd
          - 2024/week6.qmd
          - 2024/week7.qmd
          - 2024/week8.qmd
          - 2024/week9.qmd
          - 2024/week10.qmd
      - text: "2023"
        menu:
          - 2023/week1.qmd
          - 2023/week2.qmd
          - 2023/week3.qmd
          - 2023/week4.qmd
          - 2023/week5.qmd
          - 2023/week6.qmd
          - 2023/week7.qmd
          - 2023/week8.qmd
          - 2023/week9.qmd
          - 2023/week10.qmd



format:
  html:
    theme: 
      - custom.scss
    mainfont: Quicksand
    css: styles.css
    toc: true

editor: visual

