---
title: "Response"
---

```{r}
library(tidyverse)
survey_raw <- read_csv("survey.csv") %>%
  mutate(resp_id = row_number())

survey_long <- survey_raw %>% 
  pivot_longer(cols = -c(resp_id, U_G),
               names_to = "question", 
               values_to = "response")

survey_likert <- survey_long %>% 
  filter(!str_detect(question, "SCV*"))

survey_scv <- survey_long %>% 
  filter(str_detect(question, "SCV*"))

likert_levels <- c("Strongly disagree", 
                   "Disagree", 
                   "Neither agree nor disagree", 
                   "Agree", 
                   "Strongly agree")

likert_summary <- survey_likert %>% 
  drop_na(response) %>% 
  group_by(question, response) %>% 
  summarize(count = n(), .groups = "drop") %>% 
  complete(question, response, fill = list(count = 0)) %>% 
  group_by(question) %>% 
  mutate(prop = count / sum(count)) %>% 
  ungroup() %>% 
  mutate(response = factor(response, 
                           levels = c("Strongly disagree", 
                                      "Disagree", 
                                      "Neither agree nor disagree", 
                                      "Agree", 
                                      "Strongly agree")))

likert_wide <- likert_summary %>% 
  select(-count) %>% 
  pivot_wider(names_from = response, values_from = prop)
```

```{r}
library(likert)
survey_likert <- survey_raw %>% 
  dplyr::select(-starts_with("SCV"), -resp_id, -U_G) %>% 
  mutate(across(everything(), ~ factor(.x, levels = likert_levels, exclude = "NA"))) %>% 
  as.data.frame() %>% 
  likert()
plot(survey_likert,
     group.order = sort(colnames(survey_likert$items)))
```
